# .github/FUNDING.yml

# Add any platforms you use:
# patreon: your-patreon-username
ko_fi: rodrigogalura
# open_collective: your-collective

# Custom links (can include PayPal, GCash, etc.)
custom:
  # - "https://paypal.me/yourlink"
  # - "https://www.buymeacoffee.com/yourusername"
  # - "https://yourwebsite.com/support"
  # - "https://linktr.ee/yourlink"   # optional if you want one page with all methods
  # - "https://gcash.com/your-custom-link"  # replace with your GCash QR/link
