name: Pest Tests

on:
  push:
  pull_request:

jobs:
  pest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.3', '8.4']

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run Pest Tests
        run: ./vendor/bin/pest
